### ISSUE TITLE
How to use cp-profiler with fzn-gecode?

### ISSUE THREAD

**Issue by Revilotom** [cp-profiler/cp-profiler#1]
Hello, I built cp-profiler using the instructions on the README
I built gecode using these commands:
`cd gecode`
`git checkout release-6.0.1`
`mkdir build`
`cd build`
`../configure --enable-cpprofiler --disable-qt --disable-gist --enable-static`
`make`
`cp tools/flatzinc/fzn-gecode ${BIN_DIR}/fzn-gecode`

I have a .fzn file:
`predicate all_different_int(array [int] of var int: xs);
predicate gecode_global_cardinality(array[int] of var int: x, array[int] of int: cover, array[int] of var int: counts);var 1..2: x::output_var; %
var 1..2: y::output_var; %
var 2..3: z::output_var; %
constraint int_lin_eq([1,1,-1],[x,y,z],0);
solve :: int_search([x, y, z], input_order, indomain_min, complete)
 satisfy;`

I want to see the tree of the fzn file using cp-profiler.
I have tried running cp-profiler in one terminal and running the following in another terminal:
`$ fzn-gecode -cpprofiler-info true model000001.eprime.fzn`
But nothing seems to happen.

Do I need to set the `-cpprofiler-id` option when calling fzn-gecode? If so, where do I find the execution ID to set it? 

Please can someone show me an example of connecting cp-profiler with fzn-gecode?

**Comment by guidotack** [comment]
You have to use the command line option `-mode cpprofiler`.
