### ISSUE TITLE
Watching LDS and DDS

### ISSUE THREAD

**Issue by cprudhom** [cp-profiler/cp-profiler#3]
Hi,

I want to visualize three resolutions on binary constraints 8-queens problem solved with Choco3, one with a DFS, another with LDS(1) and the last one DDS(2).
DFS is ok; LDS crashes, and I can't figure out why; DDS outputs wrong labels, but I can live with that, since I believe cp-profiler is made for DFS.

I'm pretty sure Choco3 sent wrong information to cp-profiler, but since there is no log file (or I can't find it), so I can't make it works by myself.
Do I have to send some specific node when the discrepancy increases?

Thank you for your help.
FYI, here are the three set of instructions I sent to cp-profiler:

LDS(1) which crashes:
```
connector.sendNode(0, -1, -1, 2, Connector.NodeStatus.BRANCH, "ROOT", "");
connector.sendNode(1, 0, 0, 2, Connector.NodeStatus.BRANCH, "Q_0 = {1}", "");
connector.sendNode(2, 1, 0, 2, Connector.NodeStatus.BRANCH, "Q_1 = {3}", "");
connector.sendNode(3, 2, 0, 0, Connector.NodeStatus.FAILED, "Q_2 = {5}", "");
connector.sendNode(4, 0, 1, 2, Connector.NodeStatus.BRANCH, "Q_0 = {1}", "");
connector.sendNode(5, 4, 0, 2, Connector.NodeStatus.BRANCH, "Q_1 = {3}", "");
connector.sendNode(6, 5, 0, 0, Connector.NodeStatus.FAILED, "Q_2 = {5}", "");
connector.sendNode(7, 5, 1, 2, Connector.NodeStatus.BRANCH, "Q_2 \ {5}", "");
connector.sendNode(8, 7, 0, 2, Connector.NodeStatus.BRANCH, "Q_2 = {6}", "");
connector.sendNode(9, 8, 0, 0, Connector.NodeStatus.FAILED, "Q_3 = {2}", "");
connector.sendNode(10, 5, 1, 2, Connector.NodeStatus.BRANCH, "Q_1 \ {3}", "");
connector.sendNode(11, 10, 0, 2, Connector.NodeStatus.BRANCH, "Q_1 = {4}", "");
connector.sendNode(12, 11, 0, 2, Connector.NodeStatus.BRANCH, "Q_2 = {2}", "");
connector.sendNode(13, 12, 0, 0, Connector.NodeStatus.FAILED, "Q_3 = {5}", "");
connector.sendNode(14, 10, 1, 2, Connector.NodeStatus.BRANCH, "Q_0 \ {1}", "");
connector.sendNode(15, 14, 0, 2, Connector.NodeStatus.BRANCH, "Q_0 = {2}", "");
connector.sendNode(16, 15, 0, 2, Connector.NodeStatus.BRANCH, "Q_1 = {4}", "");
connector.sendNode(17, 16, 0, 2, Connector.NodeStatus.BRANCH, "Q_2 = {1}", "");
connector.sendNode(18, 17, 0, 0, Connector.NodeStatus.FAILED, "Q_3 = {3}", "");
```

DDS(2) which outputs wrong labels:
```
connector.sendNode(0, -1, -1, 2, Connector.NodeStatus.BRANCH, "ROOT", "");
connector.sendNode(1, 0, 0, 2, Connector.NodeStatus.BRANCH, "Q_0 = {1}", "");
connector.sendNode(2, 1, 0, 2, Connector.NodeStatus.BRANCH, "Q_1 = {3}", "");
connector.sendNode(3, 2, 0, 0, Connector.NodeStatus.FAILED, "Q_2 = {5}", "");
connector.sendNode(4, 0, 1, 2, Connector.NodeStatus.BRANCH, "Q_0 \ {1}", "");
connector.sendNode(5, 4, 0, 2, Connector.NodeStatus.BRANCH, "Q_0 = {2}", "");
connector.sendNode(6, 5, 0, 2, Connector.NodeStatus.BRANCH, "Q_1 = {4}", "");
connector.sendNode(7, 6, 0, 2, Connector.NodeStatus.BRANCH, "Q_2 = {1}", "");
connector.sendNode(8, 7, 0, 0, Connector.NodeStatus.FAILED, "Q_3 = {3}", "");
connector.sendNode(9, 4, 1, 2, Connector.NodeStatus.BRANCH, "Q_0 = {1}", "");
connector.sendNode(10, 9, 0, 2, Connector.NodeStatus.BRANCH, "Q_1 \ {3}", "");
connector.sendNode(11, 10, 0, 2, Connector.NodeStatus.BRANCH, "Q_1 = {4}", "");
connector.sendNode(12, 11, 0, 2, Connector.NodeStatus.BRANCH, "Q_2 = {2}", "");
connector.sendNode(13, 12, 0, 0, Connector.NodeStatus.FAILED, "Q_3 = {5}", "");
connector.sendNode(14, 10, 1, 2, Connector.NodeStatus.BRANCH, "Q_0 \ {1}", "");
connector.sendNode(15, 14, 0, 2, Connector.NodeStatus.BRANCH, "Q_0 \ {2}", "");
connector.sendNode(16, 15, 0, 2, Connector.NodeStatus.BRANCH, "Q_0 = {3}", "");
connector.sendNode(17, 16, 0, 2, Connector.NodeStatus.BRANCH, "Q_1 = {1}", "");
connector.sendNode(18, 17, 0, 2, Connector.NodeStatus.BRANCH, "Q_2 = {4}", "");
connector.sendNode(19, 18, 0, 0, Connector.NodeStatus.FAILED, "Q_3 = {2}", "");
```

**Comment by msgmaxim** [comment]
Crashing usually occurs when there is no parent for the node we are about to draw (I should probably provide a better error message for that case). In your case of LDS I can see that one of the nodes has more than 2 children, so there is no "room" for the third one. Is that normal behaviour in Choco? The profiler isn't limited in terms of the number of children nodes have, but that information has to be specified alongside with the node (in your case it is always 2) We could change that in the future. Otherwise the LDS search should work, the profiler is mostly search-independent.

For your convenience I've made `search_logger` available at https://github.com/cp-profiler/search_logger. It acts in place of the profiler (can't be run together, at least not at the same port) and prints the messages as they come from a solver. Hope that is helpful!

I will have a look at DDS next.

**Comment by cprudhom** [comment]
In LDS(1), the same sub-tree can explored more than once.
```
connector.sendNode(1, 0, 0, 2, Connector.NodeStatus.BRANCH, "Q_0 = {1}", "");
connector.sendNode(2, 1, 0, 2, Connector.NodeStatus.BRANCH, "Q_1 = {3}", "");
connector.sendNode(3, 2, 0, 0, Connector.NodeStatus.FAILED, "Q_2 = {5}", "");
connector.sendNode(4, 0, 1, 2, Connector.NodeStatus.BRANCH, "Q_0 = {1}", "");
connector.sendNode(5, 4, 0, 2, Connector.NodeStatus.BRANCH, "Q_1 = {3}", "");
connector.sendNode(6, 5, 0, 0, Connector.NodeStatus.FAILED, "Q_2 = {5}", "");
```

In that case, what should be the correct pid sent? 
Do I have to consider that extending the discrepancy is like a restart, i.e., a fresh branch is started?

**Comment by cmears** [comment]
Hi Charles,

I have a question about your LDS log above, specifically these two lines:

```
connector.sendNode(5, 4, 0, 2, Connector.NodeStatus.BRANCH, "Q_1 = {3}", "");
...
connector.sendNode(10, 5, 1, 2, Connector.NodeStatus.BRANCH, "Q_1 \ {3}", "");
```

If I've understood it right, these two are siblings, in that 5 is a left-branch and 10 is the corresponding right-branch. If that is the case, shouldn't they have the same parent (node 4)?

In answer to your question, we think that you are right that extending the discrepancy should be treated like a restart.

**Comment by cprudhom** [comment]
Yes, your right, my monitor seems buggy.
Ok for the restart, I'll try this out.
