### ISSUE TITLE
Not able to send correct restart instructions

### ISSUE THREAD

**Issue by cprudhom** [cp-profiler/cp-profiler#4]
What should be the instructions sent by a solver to indicate a restart?
I tried the followings (with java-integration):
```
connector.restart(nbrestarts);
```
I expected the new branch to be plugged to the ROOT node, but it is collapse to the last created node.

```
connector.restart(nbrestarts);
pid_stack.clear();
alt_stack.clear();
alt_stack.push(-1); // -1 is alt for the root node
pid_stack.push(-1); // -1 is pid for the root node
```
It fails. I supposed it comes from the fact that I declared the ROOT node to be made of only one child?
If so, do I have to consider a ROOT node as unbounded-ary decision?

Thanks for your help.

**Comment by msgmaxim** [comment]
As of version `1.1.0` of `cpprof-java` (just published it now) you can specify `restart_id` for every node. Doing so is actually required for correct work over the network. You still need to run `restart(0)` in the beginning of the search to announce that you are doing restarts (that will create a super-root node) and then consequently run `restart(nbrestarts)` as actual restarts happen. Here you can find a working example of restarts using the updated library: https://github.com/cp-profiler/java-integration-example/blob/master/src/main/java/com/github/cpprofiler/RestartsExample.java

**Comment by msgmaxim** [comment]
Also please update the profiler as the previous version in fact disabled restarts accidentally.
